image: node:latest


stages:
  - build
  - deploy

build:
    stage: build
    script:
        - npm install --quiet
        - npm run build-prod

deploy:
    stage: deploy
    only:
        - master
    dependencies:
        - build
    script:
        - npm run deploy